extends Node

# warning-ignore:unused_signal
signal next_turn
# warning-ignore:unused_signal
signal enter_player_turn
# warning-ignore:unused_signal
signal exit_player_turn
# warning-ignore:unused_signal
signal enter_nature_turn
# warning-ignore:unused_signal
signal exit_nature_turn
# warning-ignore:unused_signal
signal critter_died
# warning-ignore:unused_signal
signal spawn_critter
# warning-ignore:unused_signal
signal tree_died
# warning-ignore:unused_signal
signal game_finished_with_winner(winner)
